version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=30d"  # 데이터 보관 기간 설정
      - "--storage.tsdb.max-block-duration=2h"  # 블록 크기 제한

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"  
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Grafana 기본 관리자 비밀번호 설정
    depends_on:
      - prometheus  # Grafana가 Prometheus 서비스가 시작된 후 실행

 
  #TODO: 이거 메모리 너무 차지해서 노트북환경에선 테스트 못하겠다
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1  
  #   container_name: elasticsearch
  #   restart: always
  #   environment:
  #     - discovery.type=single-node  # 클러스터 모드가 아닌 싱글 노드 모드로 설정
  #     - ELASTIC_PASSWORD=changeme  # 기본 Elastic 비밀번호 설정
  #     - ES_JAVA_OPTS=-Xms1g -Xmx1g  # Elasticsearch의 힙 메모리 설정
  #   ports:
  #     - "9200:9200"  
  #     - "9300:9300"  # Elasticsearch의 클러스터 통신 포트
  #   volumes:
  #     - elasticsearch_data:/usr/share/elasticsearch/data

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.7.1  
  #   container_name: kibana
  #   restart: always
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Kibana에서 Elasticsearch와 연결
  #   ports:
  #     - "5601:5601" 
  #   depends_on:
  #     - elasticsearch  # Kibana는 Elasticsearch가 시작된 후 실행

volumes:
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local

#docker-compose up --build
# mvn spring-boot:run 스프링부트 자체는 로컬에서 실행 
#TODO: 이거 나중에 springboot도 docker에서 실행되도록 바꿀거임, h2 -> MySQL꿔서 docker로 바꾸기


#copy con local.mv.db 로컬에 테스트용 db 파일 복사