global:
  scrape_interval: 15s  # 15초마다 데이터 수집

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # 로컬에서 실행 중인 Spring Boot 접근